# Generated by Django 4.0.5 on 2022-06-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='gallery/')),
                ('image_name', models.CharField(max_length=50)),
                ('image_caption', models.CharField(max_length=255)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clone.comment')),
            ],
        ),
    ]
