# Generated by Django 4.0.5 on 2022-06-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
