# Generated by Django 4.0.5 on 2022-06-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0005_alter_comment_id_alter_image_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=255)),
                ('profile_photo', models.ImageField(default='image.jpg', upload_to='profile/')),
            ],
        ),
    ]
