# Generated by Django 4.0.5 on 2022-06-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0010_remove_post_comments_comment_post_post_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
