# Generated by Django 4.0.5 on 2022-06-07 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0011_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_name',
            new_name='name',
        ),
    ]
