# Generated by Django 4.0.5 on 2022-06-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0012_rename_image_name_post_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='name',
        ),
    ]
